Спринт 1. С чистого листа
matthewrv-practicum/s-chistogo-lista pull request #3
Opened 2024-12-28 08:43 UTC by matthewrv-practicum

2024-12-28 10:24 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Здравствуйте! У вас получилась хорошая работа!

_Что понравилось:_

- Хорошая структура HTML
- Похоже на макет
- Нет скролла от 360px и более, и все элементы отображаются корректно
- Хорошее форматирование документа
- Хорошие стили
- Используется семантика
- Используются списки

_Что необходимо исправить:_

- **Все комментарии, кроме комментариев с пометками «Можно лучше» и «Отлично». А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**











_Что можно улучшить:_

- Все комментарии «Можно лучше»

- Для более точного контроля отображения вёрстки можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для `Chrome`, для этого в фигме выделить весь макет, экспортировать его картинкой и наложить на вёрстку в браузере. Плагин позволяет наложить изображение на вёрстку в браузере, тем самым можно с легкостью подправить недочёты по отображению. А также, если включить в расширении инверсию цвета и прозрачность 50%, то соответствие по пикселям и цветам видно лучше, так как при сложении цветов получается однородный серый цвет.

- Селекторы в файле стилей должны располагаться в порядке их появления в HTML

- В любом месте в файлах CSS в проекте (кроме самого CSS файла подключения шрифтов, где указывается только название подключаемого шрифта), где указано свойство `font-family`, помимо основного шрифта также должен быть указан альтернативный шрифт и тип засечек. Это делается для того, что если по каким-то причинам основной шрифт не загрузится, то внешний вид страницы не будет изменен очень сильно. Порядок написания шрифтов: Основной шрифт, [Веб-безопасный альтернативный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/), Тип засечек. Пример: `font-family: Inter, Arial, sans-serif;` 

- Желательно использовать все классы по БЭМ.
  - https://ru.bem.info/methodology/quick-start/
  - Проверить ошибки БЭМ можно на https://nglazov.github.io/bem-validator-page/
  - Структуру можно проверить на https://yoksel.github.io/html-tree/

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того, чтобы пользователю не приходилось заново открывать сайт проекта.

**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2024-12-28 10:24 UTC, Avaakum commented on styles/style.css
> +  font-family: "EB Garamond", sans-serif;
Это шрифт с засечками - используйте значение serif в качестве альтернативы.

2024-12-28 10:24 UTC, Avaakum commented on styles/style.css
> +  font-family: "EB Garamond", sans-serif;
Это шрифт с засечками - используйте значение serif в качестве альтернативы.

2024-12-28 10:24 UTC, Avaakum commented on styles/style.css
> +  height: 20px;
**Нужно исправить:** **Высоту для текста нужно удалить** Для текста можно задать высоту строки

---

 В случае, если элемент, содержащий, например, текстовый контент ограничить по высоте - теряется масштабируемость. При редактировании (Добавлении/удалении символов) - нарушается визуальное отображение верстки, она начинает "ломаться". Старайтесь избегать фиксированных значений для ```height;```

2024-12-28 10:24 UTC, Avaakum commented on styles/style.css
> +  height: 31.5px;
**Нужно исправить:** **Высоту для текста нужно удалить** Для текста можно задать высоту строки

---

 В случае, если элемент, содержащий, например, текстовый контент ограничить по высоте - теряется масштабируемость. При редактировании (Добавлении/удалении символов) - нарушается визуальное отображение верстки, она начинает "ломаться". Старайтесь избегать фиксированных значений для ```height;```

2024-12-28 10:24 UTC, Avaakum commented on styles/style.css
> +  height: 20px;
**Нужно исправить:** **Высоту для текста нужно удалить** Для текста можно задать высоту строки

---

 В случае, если элемент, содержащий, например, текстовый контент ограничить по высоте - теряется масштабируемость. При редактировании (Добавлении/удалении символов) - нарушается визуальное отображение верстки, она начинает "ломаться". Старайтесь избегать фиксированных значений для ```height;```

2024-12-28 10:24 UTC, Avaakum commented on styles/style.css
> +.cover-title > .accent-span:nth-child(3) {
Задайте класс для элемента и стили для этого класса

---

Не следует использовать стилизацию по номеру блока, так как порядок блоков может измениться. Рекомендуется применять более гибкие подходы к стилизации, которые не зависят от конкретной нумерации блоков на странице, чтобы обеспечить устойчивость и адаптивность структуры. Более гибким решением будет воспользоваться вспомогательными классами для назначения “отличающийся” стилизации блока. А для однотипной стилизации использовать общую сущность.

2024-12-28 10:24 UTC, Avaakum commented on index.html
> +  </head>
---

**Отлично:**

Корректно заполнен `head`

2024-12-28 10:24 UTC, Avaakum commented on index.html
> +      <a class="header__logo">
---

**Отлично:**

Логотип должен быть ссылкой без атрибута href(что бы по ссылке не было перехода)  для улучшения семантики страницы.

2024-12-28 10:24 UTC, Avaakum commented on index.html
> +        <ol class="header__menu-list">
---

**Можно лучше:**

Используйте ненумерованный список ul

2024-12-28 10:24 UTC, Avaakum commented on index.html
> +          <time class="intro__date" datetime="2022-06-05">05.06.2022 г.</time>
---

**Отлично:**

Отличная семантика

2024-12-28 10:24 UTC, Avaakum commented on index.html
> +            <article class="card card_theme_dark">
---

**Отлично:**

Отличная семантика и структура

2024-12-28 10:24 UTC, Avaakum commented on index.html
> +      <ol class="footer__links">
---

**Можно лучше:**

Используйте ненумерованный список ul

2024-12-30 08:15 UTC, matthewrv-practicum commented on styles/style.css
> +.cover-title > .accent-span:nth-child(3) {
Разделил стили из этого селектора на два. Одну часть перенёс в класс `.cover`, для второй создал специальный класс

2024-12-30 08:16 UTC, matthewrv-practicum commented on styles/style.css
> +  font-family: "EB Garamond", sans-serif;
Исправил

2024-12-30 08:16 UTC, matthewrv-practicum commented on styles/style.css
> +  font-family: "EB Garamond", sans-serif;
Исправил

2024-12-30 08:16 UTC, matthewrv-practicum commented on styles/style.css
> +  height: 20px;
Исправил

2024-12-30 08:16 UTC, matthewrv-practicum commented on styles/style.css
> +  height: 31.5px;
Исправил

2024-12-30 08:16 UTC, matthewrv-practicum commented on styles/style.css
> +  height: 20px;
Исправил

2024-12-30 08:17 UTC, matthewrv-practicum commented on index.html
> +            <article class="card card_theme_dark">
:heart:

2024-12-30 08:17 UTC, matthewrv-practicum commented on index.html
> +          <time class="intro__date" datetime="2022-06-05">05.06.2022 г.</time>
:heart:

2024-12-30 08:17 UTC, matthewrv-practicum commented on index.html
> +      <ol class="footer__links">
Исправил

2024-12-30 08:17 UTC, matthewrv-practicum commented on index.html
> +        <ol class="header__menu-list">
Исправил

2024-12-30 08:17 UTC, matthewrv-practicum commented on index.html
> +      <a class="header__logo">
:heart:

2024-12-30 08:17 UTC, matthewrv-practicum commented on index.html
> +  </head>
:heart:

2024-12-31 19:29 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! 






Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 



Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)

2025-01-01 11:27 UTC, merged